import { useEffect, useRef, useCallback } from 'react'
import { getContent } from '../utils/contextContent.js'

// ── Safe array helper — never crashes on undefined ────────────
const safeArr = (v) => (Array.isArray(v) ? v : [])

// ── Plain-text report builder ─────────────────────────────────
function buildReportText(prediction, context, uploadMode, personA, personB) {
  const content = getContent(context)
  const now     = new Date()
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })

  const subjectLines = uploadMode === 'individual'
    ? [
        `  Subject A:    ${personA?.name || 'Subject A'}`,
        `  Subject B:    ${personB?.name || 'Subject B'}`,
        `  Upload Mode:  Individual Photos`,
      ]
    : [`  Upload Mode:  Couple Photo`]

  const humanLines = context === 'human' ? [
    `  Breakup Probability:   ${prediction.breakupProbability ?? '?'}%`,
    `  Relationship Strength: ${prediction.relationshipStrength ?? '?'}%`,
  ] : []

  const whoLines = safeArr(prediction.whoMoreLikelyQuestions).length > 0 ? [
    ``,
    `═══════════════════════════════════════════════`,
    ` 👀  WHO IS MORE LIKELY TO…`,
    `═══════════════════════════════════════════════`,
    ...safeArr(prediction.whoMoreLikelyQuestions).slice(0, 5).map(q => `  • ${q.q}`),
  ] : []

  return [
    `╔═══════════════════════════════════════════════╗`,
    `║         💔   OFFICIAL LOVE404 REPORT           ║`,
    `║        Generated by love404 — 100% Fake AI     ║`,
    `╚═══════════════════════════════════════════════╝`,
    ``,
    `  Generated:   ${dateStr}`,
    `  Time:        ${timeStr}`,
    `  Context:     ${context.toUpperCase()}`,
    ...subjectLines,
    ``,
    `═══════════════════════════════════════════════`,
    ` 🏆  VERDICT`,
    `═══════════════════════════════════════════════`,
    `  ${prediction.verdict ?? 'Unknown'}`,
    ``,
    `  "${prediction.funnyReason ?? ''}"`,
    ``,
    `  Overall Score:  ${prediction.overallScore ?? '?'}/100`,
    ...humanLines,
    ``,
    `═══════════════════════════════════════════════`,
    ` 📊  DETAILED METRICS`,
    `═══════════════════════════════════════════════`,
    ...safeArr(prediction.metrics).map(m =>
      `  ${m.emoji ?? ''}  ${(m.label ?? '').padEnd(26)} ${String(m.score ?? 0).padStart(3)}%  [${m.severity ?? ''}]`
    ),
    ``,
    `═══════════════════════════════════════════════`,
    ` 📝  ANALYSIS NOTES`,
    `═══════════════════════════════════════════════`,
    ...safeArr(prediction.metrics).map(m => `  • ${m.joke ?? ''}`),
    ``,
    `═══════════════════════════════════════════════`,
    ` 🌤️  CONTEXT WEATHER`,
    `═══════════════════════════════════════════════`,
    `  ${prediction.weather?.icon ?? ''} ${prediction.weather?.label ?? 'Unknown'}`,
    `  ${prediction.weather?.sub ?? ''}`,
    ``,
    `═══════════════════════════════════════════════`,
    ` 🚩  RED FLAGS`,
    `═══════════════════════════════════════════════`,
    ...safeArr(prediction.redFlags).map(f => `  ${f}`),
    ``,
    `═══════════════════════════════════════════════`,
    ` 💚  GREEN FLAGS`,
    `═══════════════════════════════════════════════`,
    ...safeArr(prediction.greenFlags).map(f => `  ${f}`),
    ``,
    `═══════════════════════════════════════════════`,
    ` 💡  EXPERT ADVICE`,
    `═══════════════════════════════════════════════`,
    `  "${prediction.advice ?? ''}"`,
    ...whoLines,
    ``,
    `═══════════════════════════════════════════════`,
    ` 🪪  ${content.cvTitle ?? 'OFFICIAL PROFILE'}`,
    `═══════════════════════════════════════════════`,
    `  Name:         ${prediction.profile?.name ?? 'Unknown'}`,
    `  Type:         ${prediction.profile?.type ?? 'Unknown'}`,
    `  Status:       ${prediction.profile?.status ?? 'Unknown'}`,
    `  Strengths:    ${safeArr(prediction.profile?.strengths).join(', ') || '—'}`,
    `  Weaknesses:   ${safeArr(prediction.profile?.weaknesses).join(', ') || '—'}`,
    `  Certification: ${prediction.profile?.certification ?? '—'}`,
    ``,
    `╔═══════════════════════════════════════════════╗`,
    `║  AI USED:            Absolutely none.          ║`,
    `║  SCIENTIFIC ACCURACY: 0%                       ║`,
    `║  CONTEXT DETECTED BY: COCO-SSD + MobileNet     ║`,
    `║  CERTIFIED BY:        International Institute  ║`,
    `║                       of Absolutely Nothing    ║`,
    `╚═══════════════════════════════════════════════╝`,
    ``,
    `⚠️  This report is 100% fake.`,
    `   For entertainment only. Please do not make`,
    `   real life decisions based on this. We beg you.`,
    ``,
    `   love404 — love404.fake`,
  ].join('\n')
}

// ── HTML report builder (includes photos) ────────────────────
function buildReportHtml(prediction, context, uploadMode, personA, personB, primaryImage, secondImage) {
  const content = getContent(context)
  const now     = new Date()
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })

  const photosHtml = (() => {
    if (!primaryImage && !secondImage) return ''
    if (uploadMode === 'individual') {
      return `
        <div class="photos">
          <div class="photo-slot">
            ${primaryImage ? `<img src="${primaryImage}" alt="${personA?.name || 'Subject A'}"/>` : '<div class="photo-placeholder">No photo</div>'}
            <span>${personA?.name || 'Subject A'}</span>
          </div>
          <div class="photo-vs">vs</div>
          <div class="photo-slot">
            ${secondImage ? `<img src="${secondImage}" alt="${personB?.name || 'Subject B'}"/>` : '<div class="photo-placeholder">No photo</div>'}
            <span>${personB?.name || 'Subject B'}</span>
          </div>
        </div>`
    }
    return `<div class="photos single"><img src="${primaryImage}" alt="Analyzed photo"/></div>`
  })()

  const metricsRows = safeArr(prediction.metrics).map(m => `
    <tr>
      <td>${m.emoji ?? ''}</td>
      <td>${m.label ?? ''}</td>
      <td class="bar-cell"><div class="bar-track"><div class="bar-fill" style="width:${m.score ?? 0}%"></div></div></td>
      <td class="score">${m.score ?? 0}%</td>
      <td class="sev sev-${(m.severity ?? '').toLowerCase()}">${m.severity ?? ''}</td>
    </tr>`).join('')

  const flagsHtml = (arr, cls) => safeArr(arr).map(f => `<li class="${cls}">${f}</li>`).join('')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>love404 — Official Report</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{background:#09090B;color:#F4F4F5;font-family:'Segoe UI',system-ui,sans-serif;padding:2rem;max-width:800px;margin:0 auto;font-size:14px;line-height:1.6}
  h1{font-size:1.6rem;font-weight:800;letter-spacing:-0.02em;margin-bottom:.25rem}
  h2{font-size:.65rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase;color:#71717A;margin:1.5rem 0 .6rem}
  .header{border-bottom:1px solid rgba(255,255,255,.08);padding-bottom:1.25rem;margin-bottom:1.5rem}
  .badge{display:inline-block;font-size:.6rem;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#71717A;background:#121216;border:1px solid rgba(255,255,255,.08);padding:2px 10px;border-radius:999px;margin-top:.4rem}
  .meta{font-size:.75rem;color:#71717A;margin-top:.5rem}
  .verdict{font-size:1.4rem;font-weight:800;color:#F4F4F5;letter-spacing:-0.02em;margin:.5rem 0 .25rem}
  .funny{color:#A1A1AA;font-style:italic;margin-bottom:.75rem}
  .score-big{font-size:2rem;font-weight:800;color:#F43F5E;margin:.25rem 0}
  .human-pills{display:flex;gap:.5rem;flex-wrap:wrap;margin-top:.25rem}
  .pill{font-size:.7rem;font-weight:600;padding:2px 10px;border-radius:999px;border:1px solid}
  .pill-rose{color:#F43F5E;background:rgba(244,63,94,.12);border-color:rgba(244,63,94,.2)}
  .pill-green{color:#22C55E;background:rgba(34,197,94,.12);border-color:rgba(34,197,94,.2)}
  .photos{display:flex;align-items:center;gap:1rem;margin:.75rem 0}
  .photos.single img{width:100%;max-height:220px;object-fit:cover;border-radius:12px;border:1px solid rgba(255,255,255,.1)}
  .photo-slot{display:flex;flex-direction:column;align-items:center;gap:.3rem;flex:1}
  .photo-slot img{width:100%;height:160px;object-fit:cover;border-radius:10px;border:1px solid rgba(255,255,255,.1)}
  .photo-placeholder{width:100%;height:160px;background:#17171C;border:1px dashed rgba(255,255,255,.1);border-radius:10px;display:flex;align-items:center;justify-content:center;color:#71717A;font-size:.75rem}
  .photo-slot span,.photo-vs{font-size:.68rem;font-weight:700;letter-spacing:.06em;text-transform:uppercase;color:#71717A}
  .photo-vs{padding:0 .25rem}
  table{width:100%;border-collapse:collapse}
  td{padding:.3rem .4rem;font-size:.8rem;vertical-align:middle}
  td:first-child{width:1.5rem;font-size:.9rem}
  .bar-cell{width:120px}
  .bar-track{background:rgba(255,255,255,.08);border-radius:999px;height:5px;overflow:hidden}
  .bar-fill{height:100%;background:linear-gradient(90deg,#F43F5E,#A855F7);border-radius:999px}
  .score{font-weight:700;font-size:.82rem;text-align:right;width:36px}
  .sev{font-size:.6rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em;text-align:right;width:60px}
  .sev-low{color:#22C55E}.sev-moderate{color:#EAB308}.sev-high{color:#F97316}.sev-critical{color:#F43F5E}
  ul{list-style:none;display:flex;flex-direction:column;gap:.3rem}
  li{font-size:.8rem;color:#A1A1AA}
  li.red::before{content:'🚩  '}
  li.green::before{content:'💚  '}
  li.note::before{content:'• '}
  .weather-row{display:flex;align-items:center;gap:.75rem}
  .weather-icon{font-size:1.75rem}
  .weather-label{font-size:.85rem;font-weight:700}
  .weather-sub{font-size:.75rem;color:#A1A1AA;font-style:italic}
  .profile-card{background:#121216;border:1px solid rgba(255,255,255,.07);border-radius:10px;padding:.875rem 1rem}
  .profile-name{font-size:.95rem;font-weight:700;margin-bottom:.1rem}
  .profile-type{font-size:.75rem;color:#F43F5E;margin-bottom:.1rem}
  .profile-status{font-size:.7rem;color:#71717A;font-style:italic}
  .flags-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}
  .footer-meta{border-top:1px solid rgba(255,255,255,.08);margin-top:1.5rem;padding-top:1rem;font-size:.7rem;color:#71717A;line-height:1.8}
  .disclaimer{font-size:.7rem;color:#71717A;text-align:center;margin-top:1rem;padding:.625rem;background:rgba(244,63,94,.06);border:1px solid rgba(244,63,94,.15);border-radius:8px}
  @media print{body{background:#fff;color:#111}.badge{background:#f5f5f5;color:#555}.profile-card{background:#f9f9f9}.bar-track{background:#e5e7eb}}
</style>
</head>
<body>

<div class="header">
  <h1>💔 Official love404 Report</h1>
  <div class="badge">FAKE AI™ · 0% SCIENTIFIC ACCURACY</div>
  <p class="meta">Generated: ${dateStr} · Context: ${context.toUpperCase()}</p>
</div>

<h2>📸 Uploaded Photo${uploadMode === 'individual' ? 's' : ''}</h2>
${photosHtml || '<p style="color:#71717A;font-size:.8rem">No photos available in report.</p>'}

<h2>🏆 Verdict</h2>
<p class="verdict">${prediction.verdict ?? 'Unknown'}</p>
<p class="funny">"${prediction.funnyReason ?? ''}"</p>
<div class="score-big">${prediction.overallScore ?? '?'}<span style="font-size:1rem;color:#71717A">/100</span></div>
${context === 'human' ? `<div class="human-pills">
  <span class="pill pill-rose">💔 Breakup ${prediction.breakupProbability ?? '?'}%</span>
  <span class="pill pill-green">❤️ Strength ${prediction.relationshipStrength ?? '?'}%</span>
</div>` : ''}

<h2>📊 Detailed Metrics</h2>
<table>${metricsRows}</table>

<h2>📝 Analysis Notes</h2>
<ul>${safeArr(prediction.metrics).map(m => `<li class="note">${m.emoji ?? ''} ${m.joke ?? ''}</li>`).join('')}</ul>

<h2>🌤️ Context Weather</h2>
<div class="weather-row">
  <span class="weather-icon">${prediction.weather?.icon ?? ''}</span>
  <div><p class="weather-label">${prediction.weather?.label ?? 'Unknown'}</p>
  <p class="weather-sub">${prediction.weather?.sub ?? ''}</p></div>
</div>

<div class="flags-grid">
  <div>
    <h2>🚩 Red Flags</h2>
    <ul>${flagsHtml(prediction.redFlags, 'red')}</ul>
  </div>
  <div>
    <h2>💚 Green Flags</h2>
    <ul>${flagsHtml(prediction.greenFlags, 'green')}</ul>
  </div>
</div>

<h2>💡 Expert Advice</h2>
<p style="font-style:italic;color:#A1A1AA">"${prediction.advice ?? ''}"</p>

${safeArr(prediction.whoMoreLikelyQuestions).length > 0 ? `
<h2>👀 Who Is More Likely To…</h2>
<ul>${safeArr(prediction.whoMoreLikelyQuestions).slice(0, 5).map(q => `<li class="note">${q.q}</li>`).join('')}</ul>` : ''}

<h2>🪪 ${content.cvTitle ?? 'Official Profile'}</h2>
<div class="profile-card">
  <p class="profile-name">${prediction.profile?.name ?? 'Unknown'}</p>
  <p class="profile-type">${prediction.profile?.type ?? ''}</p>
  <p class="profile-status">${prediction.profile?.status ?? ''}</p>
</div>

<div class="footer-meta">
  <strong>AI USED:</strong> Absolutely none.<br/>
  <strong>SCIENTIFIC ACCURACY:</strong> 0%<br/>
  <strong>CONTEXT DETECTED BY:</strong> Real AI (COCO-SSD + MobileNet)<br/>
  <strong>CERTIFIED BY:</strong> The International Institute of Absolutely Nothing
</div>

<div class="disclaimer">
  ⚠️ This report is 100% fake and generated for entertainment only.<br/>
  Please do not make real life decisions based on this. We beg you.
</div>

</body>
</html>`
}

// ── Severity colors ───────────────────────────────────────────
const SEV_COLORS = {
  Low: '#22C55E', Moderate: '#EAB308', High: '#F97316', Critical: '#F43F5E',
}

function MetricRow({ metric }) {
  const color = SEV_COLORS[metric.severity] ?? '#A1A1AA'
  return (
    <div className="report-metric-row">
      <span className="report-metric-emoji">{metric.emoji}</span>
      <span className="report-metric-label">{metric.label}</span>
      <div className="report-metric-bar-track">
        <div
          className="report-metric-bar-fill"
          style={{ width: `${metric.score}%`, background: `linear-gradient(90deg,${color}88,${color})` }}
        />
      </div>
      <span className="report-metric-score">{metric.score}%</span>
      <span className="report-metric-sev" style={{ color }}>{metric.severity}</span>
    </div>
  )
}

// ── Main modal ────────────────────────────────────────────────
export default function FullReportModal({
  prediction,
  context,
  uploadMode,
  imageObjectUrl,
  personA,
  personB,
  onClose,
}) {
  const content    = getContent(context)
  const overlayRef = useRef(null)

  // Escape key + body scroll lock
  useEffect(() => {
    const handler = (e) => { if (e.key === 'Escape') onClose() }
    window.addEventListener('keydown', handler)
    document.body.style.overflow = 'hidden'
    return () => {
      window.removeEventListener('keydown', handler)
      document.body.style.overflow = ''
    }
  }, [onClose])

  const primaryImage = uploadMode === 'individual' ? (personA?.url ?? imageObjectUrl) : imageObjectUrl
  const secondImage  = uploadMode === 'individual' ? (personB?.url ?? null) : null

  const isHuman      = context === 'human'
  const subjectNameA = personA?.name || (isHuman ? 'Person A' : 'Subject A')
  const subjectNameB = personB?.name || (isHuman ? 'Person B' : 'Subject B')

  // ── Download .txt ─────────────────────────────────────────
  const downloadTxt = useCallback(() => {
    try {
      const text = buildReportText(prediction, context, uploadMode, personA, personB)
      const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
      const url  = URL.createObjectURL(blob)
      const a    = document.createElement('a')
      a.href = url
      a.download = `love404-${context}-report.txt`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('Download failed:', err)
    }
  }, [prediction, context, uploadMode, personA, personB])

  // ── Download .html (preserves photos) ────────────────────
  const downloadHtml = useCallback(() => {
    try {
      const html = buildReportHtml(prediction, context, uploadMode, personA, personB, primaryImage, secondImage)
      const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
      const url  = URL.createObjectURL(blob)
      const a    = document.createElement('a')
      a.href = url
      a.download = `love404-${context}-report.html`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('HTML download failed:', err)
    }
  }, [prediction, context, uploadMode, personA, personB, primaryImage, secondImage])

  const handleOverlayClick = (e) => {
    if (e.target === overlayRef.current) onClose()
  }

  // Safe arrays for rendering
  const metrics    = safeArr(prediction.metrics)
  const redFlags   = safeArr(prediction.redFlags)
  const greenFlags = safeArr(prediction.greenFlags)
  const whoQs      = safeArr(prediction.whoMoreLikelyQuestions)

  return (
    <div
      ref={overlayRef}
      className="modal-overlay"
      role="dialog"
      aria-modal="true"
      aria-label="Full Report"
      tabIndex={-1}
      onClick={handleOverlayClick}
    >
      <div className="modal-box">

        {/* ── Header ──────────────────────────────────────── */}
        <div className="modal-header">
          <div>
            <span className="modal-eyebrow">OFFICIAL REPORT · {context.toUpperCase()}</span>
            <h2 className="modal-title">
              THE OFFICIAL {(content.cvTitle ?? 'REPORT').toUpperCase()}
            </h2>
          </div>
          <button className="modal-close" onClick={onClose} aria-label="Close report">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
              <line x1="2" y1="2" x2="14" y2="14" />
              <line x1="14" y1="2" x2="2" y2="14" />
            </svg>
          </button>
        </div>

        {/* ── Body ────────────────────────────────────────── */}
        <div className="modal-body">

          {/* Photos */}
          {(primaryImage || secondImage) && (
            <div className="modal-section">
              <p className="modal-section-label">
                {uploadMode === 'individual' ? 'SUBJECTS' : 'UPLOADED PHOTO'}
              </p>
              <div className="modal-photos">
                {uploadMode === 'individual' ? (
                  <>
                    <div className="modal-photo-slot">
                      {primaryImage
                        ? <img src={primaryImage} alt={subjectNameA} className="modal-photo-img" />
                        : <div className="modal-photo-placeholder">No photo</div>}
                      <span className="modal-photo-label">{subjectNameA}</span>
                    </div>
                    <div className="modal-photo-vs" aria-hidden="true">vs</div>
                    <div className="modal-photo-slot">
                      {secondImage
                        ? <img src={secondImage} alt={subjectNameB} className="modal-photo-img" />
                        : <div className="modal-photo-placeholder">No photo</div>}
                      <span className="modal-photo-label">{subjectNameB}</span>
                    </div>
                  </>
                ) : (
                  <div className="modal-photo-slot modal-photo-slot--full">
                    <img src={primaryImage} alt="Analyzed" className="modal-photo-img modal-photo-img--wide" />
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Verdict */}
          <div className="modal-section modal-verdict-section">
            <p className="modal-section-label">VERDICT</p>
            <p className="modal-verdict">{prediction.verdict}</p>
            <p className="modal-funny-reason">"{prediction.funnyReason}"</p>
            <div className="modal-overall-row">
              <span className="modal-overall-label">Overall Score</span>
              <span className="modal-overall-value">
                {prediction.overallScore}
                <span className="modal-overall-unit">/100</span>
              </span>
            </div>
            {isHuman && (
              <div className="modal-human-scores">
                <div className="modal-human-score-pill">💔 Breakup: {prediction.breakupProbability ?? '?'}%</div>
                <div className="modal-human-score-pill modal-human-score-pill--green">❤️ Strength: {prediction.relationshipStrength ?? '?'}%</div>
              </div>
            )}
          </div>

          {/* Metrics */}
          {metrics.length > 0 && (
            <div className="modal-section">
              <p className="modal-section-label">DETAILED SCORES</p>
              <div className="modal-metrics-list">
                {metrics.map(m => <MetricRow key={m.key} metric={m} />)}
              </div>
            </div>
          )}

          {/* Analysis notes */}
          {metrics.length > 0 && (
            <div className="modal-section">
              <p className="modal-section-label">ANALYSIS NOTES</p>
              <ul className="modal-notes-list">
                {metrics.map(m => (
                  <li key={m.key} className="modal-note-item">
                    <span className="modal-note-emoji">{m.emoji}</span>
                    <span>{m.joke}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Weather */}
          {prediction.weather && (
            <div className="modal-section">
              <p className="modal-section-label">CONTEXT WEATHER</p>
              <div className="modal-weather">
                <span className="modal-weather-icon">{prediction.weather.icon}</span>
                <div>
                  <p className="modal-weather-label">{prediction.weather.label}</p>
                  <p className="modal-weather-sub">{prediction.weather.sub}</p>
                </div>
              </div>
            </div>
          )}

          {/* Flags */}
          {(redFlags.length > 0 || greenFlags.length > 0) && (
            <div className="modal-flags-row">
              <div className="modal-section">
                <p className="modal-section-label">🚩 RED FLAGS</p>
                <ul className="modal-flags-list">
                  {redFlags.map((f, i) => <li key={i}>{f}</li>)}
                </ul>
              </div>
              <div className="modal-section">
                <p className="modal-section-label">💚 GREEN FLAGS</p>
                <ul className="modal-flags-list modal-flags-list--green">
                  {greenFlags.map((f, i) => <li key={i}>{f}</li>)}
                </ul>
              </div>
            </div>
          )}

          {/* Advice */}
          {prediction.advice && (
            <div className="modal-section">
              <p className="modal-section-label">💡 EXPERT ADVICE</p>
              <p className="modal-advice">"{prediction.advice}"</p>
            </div>
          )}

          {/* Who is more likely */}
          {isHuman && whoQs.length > 0 && (
            <div className="modal-section">
              <p className="modal-section-label">👀 WHO IS MORE LIKELY TO…</p>
              <ul className="modal-notes-list">
                {whoQs.slice(0, 5).map((q, i) => (
                  <li key={i} className="modal-note-item modal-note-item--plain">
                    <span className="modal-note-emoji">•</span>
                    <span>{q.q}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Profile */}
          {prediction.profile && (
            <div className="modal-section">
              <p className="modal-section-label">{content.cvTitle ?? 'OFFICIAL PROFILE'}</p>
              <div className="modal-profile">
                <p className="modal-profile-name">{prediction.profile.name}</p>
                <p className="modal-profile-type">{prediction.profile.type}</p>
                <p className="modal-profile-status">{prediction.profile.status}</p>
                {safeArr(prediction.profile.strengths).length > 0 && (
                  <div className="modal-profile-flags">
                    {safeArr(prediction.profile.strengths).map((s, i) => (
                      <span key={i} className="modal-profile-flag modal-profile-flag--strength">✓ {s}</span>
                    ))}
                    {safeArr(prediction.profile.weaknesses).map((w, i) => (
                      <span key={i} className="modal-profile-flag modal-profile-flag--weakness">✗ {w}</span>
                    ))}
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Footer meta */}
          <div className="modal-meta">
            <div className="modal-meta-row"><span>AI USED</span><span>Absolutely none.</span></div>
            <div className="modal-meta-row"><span>SCIENTIFIC ACCURACY</span><span>0%</span></div>
            <div className="modal-meta-row"><span>CONTEXT DETECTION</span><span>Real AI (COCO-SSD + MobileNet)</span></div>
            <div className="modal-meta-row"><span>RESULTS</span><span>Pure randomness</span></div>
            <div className="modal-meta-row"><span>CERTIFIED BY</span><span>International Institute of Absolutely Nothing</span></div>
          </div>

          <p className="modal-disclaimer-text">
            ⚠️ 100% fake and for entertainment only. Do not make life decisions based on this.
          </p>
        </div>

        {/* ── Footer actions ───────────────────────────────── */}
        <div className="modal-footer">
          <button className="btn btn--ghost" onClick={onClose}>✕ Close</button>
          <div className="modal-download-group">
            <button className="btn btn--ghost modal-dl-btn" onClick={downloadTxt} title="Plain text, no photos">
              ⬇️ .txt
            </button>
            <button className="btn btn--primary modal-dl-btn" onClick={downloadHtml} title="HTML report with photos">
              ⬇️ Download Report (with photos)
            </button>
          </div>
        </div>

      </div>
    </div>
  )
}
