// contextContent.js
// All category-specific content pools. Nothing here is real.

const pickRandom = (arr) => arr[Math.floor(Math.random() * arr.length)]
export { pickRandom }

// ── HUMAN ────────────────────────────────────────────────────
export const humanContent = {
  heading: 'THE RESULTS ARE IN.',
  subheading: 'We regret to inform you that our algorithm has opinions.',
  cvTitle: 'RELATIONSHIP CV',
  mainMetricLabel: 'Breakup Probability',
  mainMetricEmoji: '💔',
  loaderSteps: [
    { main: 'Scanning emotional bandwidth...', sub: 'Emotional bandwidth: questionable' },
    { main: 'Analyzing micro-expressions and eye contact...', sub: 'Eye contact detected. Suspicious.' },
    { main: 'Measuring vibe synchronization...', sub: 'Vibes: present. Barely.' },
    { main: 'Checking relationship WiFi stability...', sub: 'Signal found. Barely.' },
    { main: "Checking who replies 'K'...", sub: 'K detected.' },
    { main: 'Calculating unnecessary drama quotients...', sub: 'This may take a while.' },
    { main: 'Consulting absolutely nobody...', sub: 'Scientific accuracy: 0%' },
    { main: 'Preparing result...', sub: 'Drama levels: concerning' },
  ],
  terminalLines: [
    '> loading relationship_model...',
    '> checking vibe_matrix...',
    '> analyzing drama_index...',
    '> consulting absolutely nobody...',
    '> result preparation complete.',
  ],
  weatherOptions: [
    { icon: '⛈️', label: 'EMOTIONALLY STORMY', sub: 'Bring a therapist.' },
    { icon: '🌤️', label: 'MOSTLY CLOUDY WITH DRAMA', sub: 'Chance of argument: 87%.' },
    { icon: '🌈', label: 'SUSPICIOUSLY BRIGHT', sub: 'Too calm. Something is wrong.' },
    { icon: '🌀', label: 'CHAOTIC BUT WARM', sub: 'They fight, they love it.' },
    { icon: '🌧️', label: 'EMOTIONALLY CLOUDY', sub: 'Someone is definitely not okay.' },
    { icon: '☀️', label: 'UNNERVINGLY STABLE', sub: 'Our algorithm is impressed.' },
  ],
  redFlags: [
    '🚩 Replies with one-word answers',
    '🚩 Says "I\'m fine" but is not fine',
    '🚩 Still follows the ex on Instagram',
    '🚩 Arguments conducted entirely in memes',
    '🚩 Turns the phone face-down suspiciously',
    '🚩 Brings up the dishwasher debate again',
    '🚩 Sends "K" as a full response',
    '🚩 Hasn\'t introduced you to the parents after 2 years',
    '🚩 Their search history includes "how to ghost someone nicely"',
  ],
  greenFlags: [
    '💚 Shares food without being asked',
    '💚 Remembers important dates (mostly)',
    '💚 Actually listens sometimes',
    '💚 Communicates via words, not silence',
    '💚 Still texts goodnight',
    '💚 Knows your coffee order',
    '💚 Doesn\'t ghost after arguments',
  ],
  advice: [
    'Never argue while hungry. Eat first. Argue later. Or don\'t argue at all.',
    'If you can survive IKEA together, you can survive anything.',
    'Communication is key. So is not sending 47 messages in a row.',
    'Spend at least 10 minutes a day not looking at your phone. Together.',
    'If in doubt, bring snacks. This solves most relationship problems.',
    'Couples who laugh together, stay together. Probably.',
    'Never go to bed angry. Go to bed passive-aggressively instead.',
    'The secret to a lasting relationship is pretending you didn\'t hear that thing they just said.',
  ],
  whoMoreLikelyQuestions: [
    { q: 'Who is more likely to reply after 7 hours?' },
    { q: 'Who is more likely to say "I\'m fine" when absolutely not fine?' },
    { q: 'Who is more likely to steal the last fry?' },
    { q: 'Who is more likely to start the argument?' },
    { q: 'Who is more likely to fall asleep during a call?' },
    { q: 'Who is more likely to send a paragraph instead of "okay"?' },
    { q: 'Who is more likely to bring up something from 3 years ago?' },
    { q: 'Who is more likely to overreact about the thermostat?' },
  ],
  cvStrengths: [
    'Proficient in emotional unavailability',
    'Advanced meme communication skills',
    'Experienced in 3am text debates',
    'Certified giver of silent treatments',
    'Strong snack-sharing instincts',
    '5+ years of complicated feelings',
    'Excellent at saying "whatever you want" and meaning nothing',
  ],
  cvWeaknesses: [
    'Struggles with replying within 24 hours',
    'Known to overanalyse text punctuation',
    'Cannot survive IKEA without incident',
    'Communicates exclusively via memes under pressure',
    'Forgets important dates but remembers random trivia',
  ],
  cvStatuses: [
    'Actively complicated',
    'It\'s complicated (always)',
    'Emotionally self-employed',
    'Currently undefined',
    'Open to interpretation',
    'In a situationship',
  ],
  cvTypes: [
    'Chaotic Romantic',
    'Chronic Overthinker',
    'Serial Snack Stealer',
    'Professional Feeler',
    'Reluctant Communicator',
    'Full-Time Drama Generator',
  ],
}

// ── ANIMAL ───────────────────────────────────────────────────
export const animalContent = {
  heading: 'ANIMAL VIBE REPORT',
  subheading: 'Our algorithm has assessed the situation. Results are fluffy.',
  cvTitle: 'ANIMAL CV',
  mainMetricLabel: 'Chaos Level',
  mainMetricEmoji: '🌀',
  loaderSteps: [
    { main: 'Measuring zoomies potential...', sub: 'Zoomies: imminent.' },
    { main: 'Calculating snack motivation...', sub: 'Treat probability: very high.' },
    { main: 'Assessing chaos quotient...', sub: 'Results: chaotic.' },
    { main: 'Checking loyalty matrix...', sub: 'Loyalty: treat-dependent.' },
    { main: 'Analyzing nap compatibility...', sub: 'Nap scores: excellent.' },
    { main: 'Consulting nobody about anything...', sub: 'Scientific accuracy: 0%' },
  ],
  terminalLines: [
    '> loading animal_behavior_model...',
    '> detecting treat_motivation...',
    '> scanning chaos_level...',
    '> checking nap_schedule...',
    '> results are fluffy.',
  ],
  weatherOptions: [
    { icon: '🐾', label: 'ZOOMIES WITH A CHANCE OF SNACKS', sub: 'High chaos. High reward.' },
    { icon: '😴', label: 'NAP CONDITIONS EXCELLENT', sub: 'Zero movement detected.' },
    { icon: '🦴', label: 'TREAT-DEPENDENT FORECAST', sub: 'Motivation: snacks only.' },
    { icon: '🌀', label: 'CHAOTIC BUT WHOLESOME', sub: 'The couch is already claimed.' },
    { icon: '🐕', label: 'LOYAL WITH A CHANCE OF CHAOS', sub: 'Probably fine.' },
  ],
  redFlags: [
    '🚩 Steals food off your plate',
    '🚩 Ignores commands selectively',
    '🚩 Occupies the entire bed',
    '🚩 Performs zoomies at 3am',
    '🚩 Has claimed the best seat',
    '🚩 Attention seeking at all times',
    '🚩 Suspicious interest in the neighbour\'s yard',
  ],
  greenFlags: [
    '💚 Shares snacks occasionally',
    '💚 Loyal energy (treat-dependent)',
    '💚 Excellent nap support',
    '💚 Will sit on your feet to keep them warm',
    '💚 Excellent listener. Cannot respond.',
    '💚 Very good at looking innocent',
  ],
  advice: [
    'More treats. This is always the solution.',
    'If they\'re ignoring you, you probably forgot the snacks.',
    'Naps fix most things. Verified independently.',
    'The zoomies have a purpose. We don\'t know what it is.',
    'Their loyalty is real. It is also treat-dependent. Both are true.',
    'Let them claim the couch. Pick your battles.',
    'Communication consists primarily of staring. This is enough.',
  ],
  cvStrengths: [
    'Elite-level napping',
    'Exceptional zoomie execution',
    'Unmatched loyalty (for snacks)',
    'Advanced attention-seeking techniques',
    'World-class staring skills',
    'Certified chaos generator',
  ],
  cvWeaknesses: [
    'Selective hearing',
    'Snack obsession (clinical)',
    'Occupies 90% of available furniture',
    'Cannot be trusted near unattended food',
    'Zoomies timing is unpredictable',
  ],
  cvStatuses: [
    'Currently napping',
    'Awaiting snacks',
    'In full chaos mode',
    'Available for cuddles',
    'Monitoring the situation',
  ],
  cvTypes: [
    'Professional Napper',
    'Chaos Engineer',
    'Snack Enthusiast',
    'Loyal but Treat-Dependent',
    'Full-Time Zoomies Practitioner',
  ],
}

// ── FRUIT ────────────────────────────────────────────────────
export const fruitContent = {
  heading: 'THE FRUIT RESULTS ARE IN.',
  subheading: 'Our algorithm has assessed your fruit. Results are juicy.',
  cvTitle: 'FRUIT CV',
  mainMetricLabel: 'Juiciness',
  mainMetricEmoji: '💧',
  loaderSteps: [
    { main: 'Checking ripeness...', sub: 'Ripeness: debatable.' },
    { main: 'Measuring juiciness...', sub: 'Juiciness: dangerously high.' },
    { main: 'Calculating snack potential...', sub: 'Snack potential: elevated.' },
    { main: 'Assessing shelf-life situation...', sub: 'Shelf life: limited.' },
    { main: 'Consulting the fruit bowl...', sub: 'Scientific accuracy: 0%' },
    { main: 'Preparing fruit report...', sub: 'Results will be delicious.' },
  ],
  terminalLines: [
    '> loading fruit_analysis_model...',
    '> checking ripeness_index...',
    '> measuring juiciness_level...',
    '> calculating snack_potential...',
    '> results are juicy.',
  ],
  weatherOptions: [
    { icon: '🍓', label: 'JUICY WITH A CHANCE OF SPOILAGE', sub: 'Act fast.' },
    { icon: '🌡️', label: 'RIPENING CONDITIONS OPTIMAL', sub: 'For now.' },
    { icon: '☀️', label: 'SWEET BUT UNSTABLE', sub: 'The sweetness won\'t last.' },
    { icon: '🧊', label: 'KEEP REFRIGERATED', sub: 'Or consequences.' },
    { icon: '🍉', label: 'EXTREMELY TROPICAL', sub: 'No notes.' },
  ],
  redFlags: [
    '🚩 Bruises easily',
    '🚩 Getting left in the fridge indefinitely',
    '🚩 Commitment issues with ripening',
    '🚩 Mysteriously disappearing from the bowl',
    '🚩 Shelf-life anxiety',
    '🚩 Suspicious browning at the edges',
  ],
  greenFlags: [
    '💚 Naturally sweet',
    '💚 Excellent snack compatibility',
    '💚 Strong smoothie potential',
    '💚 Juicy under pressure',
    '💚 Travels well',
    '💚 No artificial flavourings',
  ],
  advice: [
    'Stay cool. Literally. Refrigeration recommended.',
    'Peak ripeness is a window. Do not miss it.',
    'Strong smoothie energy. Embrace your destiny.',
    'Bruises are character. Probably.',
    'The sweetest ones go first. Act accordingly.',
    'Not all fruit was meant to share a bowl. And that\'s okay.',
  ],
  cvStrengths: [
    'Naturally sweet disposition',
    'Excellent snack credentials',
    '100% organic personality',
    'Strong visual presence',
    'Smoothie-compatible',
  ],
  cvWeaknesses: [
    'Short shelf life',
    'Bruises under social pressure',
    'Ripening timeline unclear',
    'Attracts fruit flies',
  ],
  cvStatuses: [
    'Currently ripening',
    'Peak sweetness imminent',
    'Slightly overripe but still good',
    'Refrigeration recommended',
    'Best before: unknown',
  ],
  cvTypes: [
    'Tropical Complication',
    'Sweet but Chaotic',
    'Classic with Issues',
    'Premium Snack Energy',
    'Seasonal Situationship',
  ],
}

// ── FOOD ─────────────────────────────────────────────────────
export const foodContent = {
  heading: 'THE FOOD RESULTS ARE IN.',
  subheading: 'Our algorithm has tasted the situation. Results are spicy.',
  cvTitle: 'FOOD CV',
  mainMetricLabel: 'Flavor',
  mainMetricEmoji: '🔥',
  loaderSteps: [
    { main: 'Checking seasoning...', sub: 'Needs more salt. Probably.' },
    { main: 'Measuring crunch levels...', sub: 'Crunch: adequate.' },
    { main: 'Calculating snack potential...', sub: 'Snack potential: dangerous.' },
    { main: 'Assessing spice situation...', sub: 'Spice: controversial.' },
    { main: 'Consulting the kitchen...', sub: 'Scientific accuracy: 0%' },
    { main: 'Preparing food report...', sub: 'Results will be flavorful.' },
  ],
  terminalLines: [
    '> loading food_analysis_model...',
    '> checking seasoning_levels...',
    '> measuring flavor_index...',
    '> calculating mess_potential...',
    '> results are delicious.',
  ],
  weatherOptions: [
    { icon: '🌶️', label: 'SPICY WITH A CHANCE OF CHAOS', sub: 'Handle with care.' },
    { icon: '🍕', label: 'PERFECTLY CHAOTIC', sub: 'No judgement.' },
    { icon: '🧊', label: 'REQUIRES REHEATING', sub: 'Energy levels low.' },
    { icon: '🔥', label: 'EXTREMELY FLAVORFUL', sub: 'No notes. Perfection.' },
    { icon: '🤔', label: 'NEEDS MORE SEASONING', sub: 'Something is missing.' },
  ],
  redFlags: [
    '🚩 Gets cold too quickly',
    '🚩 Someone is stealing the last bite',
    '🚩 Spice level: undisclosed',
    '🚩 Messier than expected',
    '🚩 Doesn\'t reheat well',
    '🚩 Missing key ingredients',
  ],
  greenFlags: [
    '💚 Comforting under pressure',
    '💚 Well-seasoned personality',
    '💚 Easy to share',
    '💚 Consistent flavor',
    '💚 Strong comfort-food energy',
    '💚 Worth the mess',
  ],
  advice: [
    'Add seasoning before making major decisions.',
    'Never share food unless you mean it. This is serious.',
    'The last bite belongs to no one. And everyone.',
    'Spice is subjective. Remind yourself of this.',
    'Comfort food exists for a reason. Use it.',
    'Good food fixes most moods. Data supports this.',
  ],
  cvStrengths: [
    'Exceptional flavor profile',
    'Strong comfort-food credentials',
    'Reliable in a crisis',
    'Shareable (sometimes)',
    'Consistent taste',
  ],
  cvWeaknesses: [
    'Gets cold at inconvenient moments',
    'Spice level disputes frequent',
    'Last bite always contested',
    'Messier than advertised',
  ],
  cvStatuses: [
    'Currently warm',
    'Slightly overcooked but fine',
    'Best served immediately',
    'Reheating in progress',
    'Needs more seasoning',
  ],
  cvTypes: [
    'Chaotic Comfort Food',
    'Premium Snack Energy',
    'Unexpectedly Spicy',
    'Reliable Classic',
    'Messy but Worth It',
  ],
}

// ── PET ──────────────────────────────────────────────────────
export const petContent = {
  heading: 'PET COMPATIBILITY REPORT',
  subheading: 'Our algorithm has assessed your companion. Results are adorable.',
  cvTitle: 'PET CV',
  mainMetricLabel: 'Chaos Level',
  mainMetricEmoji: '🌀',
  loaderSteps: [
    { main: 'Measuring cuteness levels...', sub: 'Cuteness: dangerously high.' },
    { main: 'Checking chaos potential...', sub: 'Chaos: confirmed.' },
    { main: 'Assessing snack motivation...', sub: 'Snack drive: maximum.' },
    { main: 'Evaluating attention-seeking index...', sub: 'Very attention-seeking.' },
    { main: 'Confirming nap schedule...', sub: 'Naps: always.' },
    { main: 'Preparing pet report...', sub: 'Results are fluffy.' },
  ],
  terminalLines: [
    '> loading pet_analysis_model...',
    '> detecting chaos_level...',
    '> checking snack_motivation...',
    '> scanning attention_demand...',
    '> results: maximum cuteness.',
  ],
  weatherOptions: [
    { icon: '🐾', label: 'CHAOTIC WITH CUDDLE POTENTIAL', sub: 'Worth it.' },
    { icon: '😴', label: 'NAP CONDITIONS PERFECT', sub: 'All day napping confirmed.' },
    { icon: '🦴', label: 'TREAT-DEPENDENT FORECAST', sub: 'Snacks are the solution.' },
    { icon: '😼', label: 'HIGH ATTITUDE', sub: 'They know what they are.' },
    { icon: '🐕', label: 'WHOLESOME CHAOS', sub: 'Loveable but dangerous.' },
  ],
  redFlags: [
    '🚩 Expects snacks for doing absolutely nothing',
    '🚩 Judges you silently',
    '🚩 Too much attitude for this relationship',
    '🚩 Claims the entire bed',
    '🚩 Selective attention to commands',
    '🚩 Suspicious midnight activity',
  ],
  greenFlags: [
    '💚 Will sit on your lap uninvited',
    '💚 Loyal beyond reason',
    '💚 Excellent emotional support',
    '💚 No judgment (visible)',
    '💚 Nap schedule is inspiring',
    '💚 100% honest with their feelings',
  ],
  advice: [
    'More treats. This is always the answer.',
    'The chaos is part of the deal. Accept it.',
    'They know when you\'re sad. That\'s enough.',
    'Let them have the blanket. It\'s not worth it.',
    'Nap together whenever possible.',
    'They\'re not ignoring you. They\'re thinking.',
  ],
  cvStrengths: [
    'Elite-level cuteness',
    'Unconditional loyalty (treat-dependent)',
    'Advanced cuddling skills',
    'Master of the sad-eyes technique',
    'Certified chaos generator',
  ],
  cvWeaknesses: [
    'Snack obsession extreme',
    'Attention demands non-negotiable',
    'Furniture ownership disputed',
    'Midnight chaos unpredictable',
  ],
  cvStatuses: [
    'Currently demanding attention',
    'Napping (do not disturb)',
    'Awaiting treats',
    'In full chaos mode',
    'Pretending to be innocent',
  ],
  cvTypes: [
    'Certified Chaos Agent',
    'Professional Cuddle Partner',
    'Treat Acquisition Specialist',
    'Luxury Napper',
    'Emotional Support Chaos',
  ],
}

// ── NATURE ───────────────────────────────────────────────────
export const natureContent = {
  heading: 'NATURE VIBE ANALYSIS',
  subheading: 'Our algorithm has assessed the outdoors. Impressively peaceful.',
  cvTitle: 'NATURE CV',
  mainMetricLabel: 'Drama',
  mainMetricEmoji: '🌩️',
  loaderSteps: [
    { main: 'Checking atmospheric drama...', sub: 'Drama: weather-dependent.' },
    { main: 'Measuring peacefulness...', sub: 'Surprisingly peaceful.' },
    { main: 'Calculating chaos potential...', sub: 'Chaos: occasional.' },
    { main: 'Assessing seasonal mood...', sub: 'Mood: complicated.' },
    { main: 'Consulting the wind...', sub: 'The wind had no comment.' },
    { main: 'Preparing nature report...', sub: 'Results: natural.' },
  ],
  terminalLines: [
    '> loading nature_analysis_model...',
    '> checking atmospheric_drama...',
    '> measuring peacefulness_index...',
    '> consulting the wind...',
    '> the wind had no comment.',
  ],
  weatherOptions: [
    { icon: '🌿', label: 'PEACEFULLY CHAOTIC', sub: 'Somehow both at once.' },
    { icon: '⛈️', label: 'EMOTIONALLY TIDAL', sub: 'Drama incoming.' },
    { icon: '🌊', label: 'DEEPLY TURBULENT', sub: 'Respect it.' },
    { icon: '☀️', label: 'UNNERVINGLY CALM', sub: 'Too calm.' },
    { icon: '🌋', label: 'EXTREMELY VOLATILE', sub: 'Stand back.' },
    { icon: '🌸', label: 'BEAUTIFULLY SEASONAL', sub: 'Won\'t last.' },
  ],
  redFlags: [
    '🚩 Unpredictable weather patterns',
    '🚩 Cannot be controlled',
    '🚩 Seasonal mood swings',
    '🚩 High drama potential (volcano)',
    '🚩 Gets dark early',
  ],
  greenFlags: [
    '💚 Extremely beautiful',
    '💚 Zero communication issues',
    '💚 No drama unless volcanic',
    '💚 Consistently fresh air',
    '💚 Genuinely calming',
    '💚 Has been here longer than everything',
  ],
  advice: [
    'Touch grass. Literally. It helps.',
    'Nature doesn\'t overthink. Take notes.',
    'Stand outside for 5 minutes. Problems get smaller.',
    'The weather doesn\'t apologize. Neither should you (sometimes).',
    'Seasonal changes are natural. In relationships too.',
    'Sometimes the most peaceful thing is just existing quietly.',
  ],
  cvStrengths: [
    'Eternal patience',
    'Zero social media presence',
    'Consistently beautiful',
    'No communication issues',
    'Has been around longer than everyone',
  ],
  cvWeaknesses: [
    'Weather is unpredictable',
    'Cannot be scheduled',
    'Occasional volcanic events',
    'Seasonal instability',
  ],
  cvStatuses: [
    'Eternally existing',
    'Currently photosynthesizing',
    'Awaiting spring',
    'Suspiciously calm',
    'Actively dramatic (storm incoming)',
  ],
  cvTypes: [
    'Ancient and Unbothered',
    'Seasonal Chaos Entity',
    'Peaceful Until Volcanic',
    'Zero Communication Required',
    'Naturally Premium',
  ],
}

// ── VEHICLE ──────────────────────────────────────────────────
export const vehicleContent = {
  heading: 'VEHICLE COMPATIBILITY REPORT',
  subheading: 'Our algorithm has assessed your vehicle. Results are motorized.',
  cvTitle: 'VEHICLE CV',
  mainMetricLabel: 'Road Rage',
  mainMetricEmoji: '🚗',
  loaderSteps: [
    { main: 'Checking fuel situation...', sub: 'Fuel: adequate.' },
    { main: 'Measuring road rage potential...', sub: 'Road rage: elevated.' },
    { main: 'Assessing parking ability...', sub: 'Parking: questionable.' },
    { main: 'Calculating speed confidence...', sub: 'Speed: debatable.' },
    { main: 'Consulting the GPS...', sub: 'GPS: recalculating.' },
    { main: 'Preparing vehicle report...', sub: 'Results are motorized.' },
  ],
  terminalLines: [
    '> loading vehicle_analysis_model...',
    '> checking road_rage_index...',
    '> measuring reliability_score...',
    '> GPS: still recalculating...',
    '> results ready. Use indicators.',
  ],
  weatherOptions: [
    { icon: '🚗', label: 'HEAVY TRAFFIC OF FEELINGS', sub: 'Merge carefully.' },
    { icon: '⛽', label: 'RUNNING LOW ON FUEL', sub: 'Refill recommended.' },
    { icon: '🛣️', label: 'CLEAR ROADS AHEAD', sub: 'Suspiciously smooth.' },
    { icon: '🌧️', label: 'VISIBILITY REDUCED', sub: 'Slow down.' },
    { icon: '🚦', label: 'TRAFFIC JAM OF DECISIONS', sub: 'Proceed with caution.' },
  ],
  redFlags: [
    '🚩 Refuses to use indicators',
    '🚩 Parks in two spaces',
    '🚩 Excessive honking',
    '🚩 Road rage at minor inconveniences',
    '🚩 Ignores the GPS',
    '🚩 Never checks the fuel gauge',
  ],
  greenFlags: [
    '💚 Reliable on long journeys',
    '💚 Uses indicators correctly',
    '💚 Strong road-trip potential',
    '💚 Comfortable seats',
    '💚 Good fuel efficiency',
    '💚 No suspicious noises',
  ],
  advice: [
    'Use your indicators. Please.',
    'Road rage solves nothing. Proven repeatedly.',
    'Check the fuel before long journeys. Basic.',
    'The GPS is not the enemy. Trust it occasionally.',
    'Parking is a skill. Practice it.',
    'A good playlist solves most driving issues.',
  ],
  cvStrengths: [
    'Strong road presence',
    'Reliable in most weather',
    'Good first impression',
    'Fuel-efficient personality',
    'Excellent road-trip energy',
  ],
  cvWeaknesses: [
    'Road rage incidents',
    'Indicator usage: selective',
    'Parking record: concerning',
    'Fuel gauge: frequently ignored',
  ],
  cvStatuses: [
    'Currently idling',
    'Recalculating route',
    'Stuck in traffic',
    'Road-trip ready',
    'Needs a service',
  ],
  cvTypes: [
    'Reliable Classic',
    'High-Speed Situationship',
    'Chaotic Daily Driver',
    'Premium Road Presence',
    'Needs Work But Worth It',
  ],
}

// ── OBJECT ───────────────────────────────────────────────────
export const objectContent = {
  heading: 'OBJECT PERSONALITY REPORT',
  subheading: 'Our algorithm has analyzed your object. Results are existential.',
  cvTitle: 'OBJECT CV',
  mainMetricLabel: 'Main Character Energy',
  mainMetricEmoji: '✨',
  loaderSteps: [
    { main: 'Assessing usefulness...', sub: 'Usefulness: unclear.' },
    { main: 'Measuring main character energy...', sub: 'Very main character.' },
    { main: 'Checking durability...', sub: 'Durability: we\'ll see.' },
    { main: 'Calculating confusion index...', sub: 'Confusion: high.' },
    { main: 'Consulting the object itself...', sub: 'No response received.' },
    { main: 'Preparing object report...', sub: 'Results are material.' },
  ],
  terminalLines: [
    '> loading object_analysis_model...',
    '> checking main_character_energy...',
    '> measuring usefulness_index...',
    '> consulting object: no response...',
    '> results: existential.',
  ],
  weatherOptions: [
    { icon: '📦', label: 'UNDEFINED CONDITIONS', sub: 'Much like its purpose.' },
    { icon: '✨', label: 'MAIN CHARACTER ENERGY', sub: 'Inexplicably confident.' },
    { icon: '🌫️', label: 'PURPOSE UNCLEAR', sub: 'But somehow iconic.' },
    { icon: '⚡', label: 'UNEXPECTEDLY ELECTRIC', sub: 'Surprising personality.' },
    { icon: '🔮', label: 'MYSTERIOUSLY FUNCTIONAL', sub: 'Somehow it works.' },
  ],
  redFlags: [
    '🚩 Purpose unclear',
    '🚩 Takes up too much space',
    '🚩 Has seen things',
    '🚩 Refuses to be categorized',
    '🚩 Main character energy (unchecked)',
    '🚩 Functionality: debated',
  ],
  greenFlags: [
    '💚 Extremely confident',
    '💚 Has its own aesthetic',
    '💚 Doesn\'t need validation',
    '💚 Durable (probably)',
    '💚 Has a story to tell',
    '💚 Iconic without trying',
  ],
  advice: [
    'Every object has a purpose. Yours may just be vibes.',
    'Embrace the confusion. It\'s part of the charm.',
    'Functionality is optional. Personality is not.',
    'Don\'t let anyone tell you what you are. You know.',
    'Main character energy is a gift. Use it responsibly.',
    'Some things exist just to exist. That is enough.',
  ],
  cvStrengths: [
    'Undeniable presence',
    'Strong aesthetic choices',
    'Does not require approval',
    'Iconic without explanation',
    'Durability: TBD',
  ],
  cvWeaknesses: [
    'Purpose frequently questioned',
    'Takes up space',
    'Cannot communicate verbally',
    'Functionality disputed',
  ],
  cvStatuses: [
    'Existing confidently',
    'Currently decorative',
    'Purpose pending',
    'Available for interpretation',
    'Extremely itself',
  ],
  cvTypes: [
    'Mysterious Everyday Icon',
    'Functional Chaos Entity',
    'Decorative Main Character',
    'Usefully Confusing',
    'Existentially Premium',
  ],
}

// ── PLANT ────────────────────────────────────────────────────
export const plantContent = {
  heading: 'PLANT PERSONALITY ANALYSIS',
  subheading: 'Our algorithm has assessed your plant. It has opinions.',
  cvTitle: 'PLANT CV',
  mainMetricLabel: 'Growth Energy',
  mainMetricEmoji: '🌱',
  loaderSteps: [
    { main: 'Checking photosynthesis levels...', sub: 'Sunlight: required.' },
    { main: 'Measuring growth potential...', sub: 'Growth: slow but steady.' },
    { main: 'Assessing watering schedule...', sub: 'Watered: recently (maybe).' },
    { main: 'Calculating leaf drama...', sub: 'Drama: photosynthesis-related.' },
    { main: 'Consulting the soil...', sub: 'Soil: no comment.' },
    { main: 'Preparing plant report...', sub: 'Results are green.' },
  ],
  terminalLines: [
    '> loading plant_analysis_model...',
    '> checking photosynthesis_index...',
    '> measuring growth_potential...',
    '> consulting the soil: silent...',
    '> results: surprisingly dramatic.',
  ],
  weatherOptions: [
    { icon: '🌿', label: 'GROWING STEADILY', sub: 'Against all odds.' },
    { icon: '💧', label: 'NEEDS WATERING', sub: 'Urgently.' },
    { icon: '☀️', label: 'THRIVING IN SUNLIGHT', sub: 'Finally.' },
    { icon: '🍂', label: 'SEASONAL COMPLICATIONS', sub: 'Not ideal.' },
    { icon: '🌱', label: 'JUST GETTING STARTED', sub: 'Patience required.' },
  ],
  redFlags: [
    '🚩 Demands constant watering',
    '🚩 Wilts dramatically for attention',
    '🚩 Drops leaves when upset',
    '🚩 Seasonal mood issues',
    '🚩 Needs specific sunlight conditions',
  ],
  greenFlags: [
    '💚 Produces oxygen (helpful)',
    '💚 Doesn\'t complain verbally',
    '💚 Visually calming',
    '💚 Low maintenance (ideally)',
    '💚 Improves any room',
    '💚 Silently thriving',
  ],
  advice: [
    'Water it. Regularly. On purpose.',
    'Plants need light, not pressure.',
    'Growth is slow. That\'s fine.',
    'Not every plant needs the same care. Figure it out.',
    'Talking to plants helps. Mostly it helps you.',
    'Some plants thrive on neglect. Identify yours.',
  ],
  cvStrengths: [
    'Silently calming presence',
    'Oxygen production',
    'Minimal verbal complaints',
    'Strong aesthetic value',
    'Patient growth strategy',
  ],
  cvWeaknesses: [
    'Watering dependency',
    'Sunlight requirements non-negotiable',
    'Seasonal emotional instability',
    'Drops leaves under pressure',
  ],
  cvStatuses: [
    'Currently photosynthesizing',
    'Awaiting water',
    'Thriving (barely)',
    'Seasonally adjusting',
    'Silently growing',
  ],
  cvTypes: [
    'Patient Long-Term Investment',
    'Dramatic Houseplant',
    'Low-Maintenance (Allegedly)',
    'Silently Thriving',
    'High-Maintenance Beauty',
  ],
}

// ── UNKNOWN ──────────────────────────────────────────────────
export const unknownContent = {
  heading: 'UNKNOWN ENTITY REPORT',
  subheading: 'Our algorithm has encountered something. It has no idea what.',
  cvTitle: 'MYSTERY CV',
  mainMetricLabel: 'Confusion Index',
  mainMetricEmoji: '❓',
  loaderSteps: [
    { main: 'Attempting to identify subject...', sub: 'Context confidence: 3%.' },
    { main: 'Consulting the algorithm...', sub: 'Algorithm: also confused.' },
    { main: 'Checking universal database...', sub: 'Database: no match.' },
    { main: 'Requesting a vacation...', sub: 'Request: approved.' },
    { main: 'Accepting mystery...', sub: 'Acceptance achieved.' },
    { main: 'Generating result anyway...', sub: 'Results: questionable.' },
  ],
  terminalLines: [
    '> loading unknown_entity_model...',
    '> context_confidence: 3%...',
    '> database: no match found...',
    '> algorithm: also confused...',
    '> generating result anyway.',
  ],
  weatherOptions: [
    { icon: '❓', label: 'DEEPLY UNDEFINED', sub: 'No further information.' },
    { icon: '🌫️', label: 'CONTEXT NOT FOUND', sub: 'Our algorithm gave up.' },
    { icon: '✨', label: 'SOMEHOW IMPRESSIVE', sub: 'For reasons unknown.' },
    { icon: '🌀', label: 'MYSTERIOUS CONDITIONS', sub: 'Undefined but present.' },
  ],
  redFlags: [
    '🚩 Cannot be classified',
    '🚩 Defies categorization',
    '🚩 Algorithm confusion: critical',
    '🚩 Context: missing',
  ],
  greenFlags: [
    '💚 Has genuine personality',
    '💚 Impressively undefined',
    '💚 Doesn\'t need a category',
    '💚 Mysterious appeal',
    '💚 Our algorithm respects it',
  ],
  advice: [
    'Whatever this is, it has personality. That\'s enough.',
    'Not everything needs a label. Be the mystery.',
    'Our algorithm gave up. That\'s actually impressive.',
    'Context confidence: 3%. Confidence: 100%.',
    'Unknown entities are the most interesting kind.',
    'We have no idea what this is and we respect it.',
  ],
  cvStrengths: [
    'Completely undefined',
    'Impressively mysterious',
    'Defies all categorization',
    'Unique beyond comparison',
    'Algorithm-breaking personality',
  ],
  cvWeaknesses: [
    'Context unclear',
    'Classification impossible',
    'Difficult to explain at parties',
  ],
  cvStatuses: [
    'Magnificently undefined',
    'Currently mysterious',
    'Existing defiantly',
    'Impossible to categorize',
    'Unknown but present',
  ],
  cvTypes: [
    'Enigmatic Entity',
    'Undefined But Iconic',
    'Algorithm Breaker',
    'Mystery Premium',
    'Categorically Uncategorizable',
  ],
}

// ── CONTENT MAP ──────────────────────────────────────────────
export const CONTENT_BY_CONTEXT = {
  human:   humanContent,
  animal:  animalContent,
  fruit:   fruitContent,
  food:    foodContent,
  pet:     petContent,
  nature:  natureContent,
  vehicle: vehicleContent,
  plant:   plantContent,
  object:  objectContent,
  unknown: unknownContent,
}

export function getContent(context) {
  return CONTENT_BY_CONTEXT[context] ?? unknownContent
}
