/**
 * reportGenerator.js
 * Generates plain-text and HTML reports from the current prediction result.
 * Never calls generatePrediction() — always uses the result passed in.
 */

const safeArr = (v) => (Array.isArray(v) ? v : [])

const CONTEXT_REPORT_TITLES = {
  human:   '💔 RELATIONSHIP ANALYSIS REPORT',
  animal:  '🐾 ANIMAL COMPATIBILITY REPORT',
  fruit:   '🍎 FRUIT COMPATIBILITY REPORT',
  food:    '🍕 FOOD COMPATIBILITY REPORT',
  pet:     '🐾 PET COMPATIBILITY REPORT',
  nature:  '🌿 NATURE VIBE REPORT',
  vehicle: '🚗 VEHICLE COMPATIBILITY REPORT',
  plant:   '🪴 PLANT PERSONALITY REPORT',
  object:  '📦 OBJECT PERSONALITY REPORT',
  unknown: '❓ UNKNOWN ENTITY REPORT',
}

export function getReportTitle(context) {
  return CONTEXT_REPORT_TITLES[context] ?? '📊 ANALYSIS REPORT'
}

export function buildPlainTextReport(prediction, context, uploadMode, personA, personB) {
  const now     = new Date()
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
  const title   = getReportTitle(context)

  const subjectLines = uploadMode === 'individual'
    ? [
        `  Subject A:    ${personA?.name || 'Subject A'}`,
        `  Subject B:    ${personB?.name || 'Subject B'}`,
        `  Upload Mode:  Individual Photos`,
      ]
    : ['  Upload Mode:  Single Photo']

  const humanLines = context === 'human' ? [
    `  Breakup Probability:   ${prediction.breakupProbability ?? '?'}%`,
    `  Relationship Strength: ${prediction.relationshipStrength ?? '?'}%`,
  ] : []

  const whoLines = safeArr(prediction.whoMoreLikelyQuestions).length > 0 ? [
    '',
    '═══════════════════════════════════════════════',
    ' 👀  WHO IS MORE LIKELY TO…',
    '═══════════════════════════════════════════════',
    ...safeArr(prediction.whoMoreLikelyQuestions).slice(0, 5).map(q => `  • ${q.q}`),
  ] : []

  const lines = [
    '╔═══════════════════════════════════════════════╗',
    `║         💔   OFFICIAL LOVE404 REPORT           ║`,
    `║        Generated by love404 — 100% Fake AI     ║`,
    '╚═══════════════════════════════════════════════╝',
    '',
    `  ${title}`,
    '',
    `  Generated:   ${dateStr}`,
    `  Time:        ${timeStr}`,
    `  Context:     ${context.toUpperCase()}`,
    ...subjectLines,
    '',
    '═══════════════════════════════════════════════',
    ' 🏆  VERDICT',
    '═══════════════════════════════════════════════',
    `  ${prediction.verdict ?? 'Unknown'}`,
    '',
    `  "${prediction.funnyReason ?? ''}"`,
    '',
    `  Overall Score:  ${prediction.overallScore ?? '?'}/100`,
    ...humanLines,
    '',
    '═══════════════════════════════════════════════',
    ' 📊  DETAILED METRICS',
    '═══════════════════════════════════════════════',
    ...safeArr(prediction.metrics).map(m =>
      `  ${m.emoji ?? ''}  ${(m.label ?? '').padEnd(26)} ${String(m.score ?? 0).padStart(3)}%  [${m.severity ?? ''}]`
    ),
    '',
    '═══════════════════════════════════════════════',
    ' 📝  ANALYSIS NOTES',
    '═══════════════════════════════════════════════',
    ...safeArr(prediction.metrics).map(m => `  • ${m.joke ?? ''}`),
    '',
    '═══════════════════════════════════════════════',
    ` ${prediction.weather?.icon ?? ''} CONTEXT WEATHER`,
    '═══════════════════════════════════════════════',
    `  ${prediction.weather?.label ?? 'Unknown'}`,
    `  ${prediction.weather?.sub ?? ''}`,
    '',
    '═══════════════════════════════════════════════',
    ' 🚩  RED FLAGS',
    '═══════════════════════════════════════════════',
    ...safeArr(prediction.redFlags).map(f => `  ${f}`),
    '',
    '═══════════════════════════════════════════════',
    ' 💚  GREEN FLAGS',
    '═══════════════════════════════════════════════',
    ...safeArr(prediction.greenFlags).map(f => `  ${f}`),
    '',
    '═══════════════════════════════════════════════',
    ' 💡  EXPERT ADVICE',
    '═══════════════════════════════════════════════',
    `  "${prediction.advice ?? ''}"`,
    ...whoLines,
    '',
    '═══════════════════════════════════════════════',
    ' 🪪  OFFICIAL PROFILE',
    '═══════════════════════════════════════════════',
    `  Name:         ${prediction.profile?.name ?? 'Unknown'}`,
    `  Type:         ${prediction.profile?.type ?? 'Unknown'}`,
    `  Status:       ${prediction.profile?.status ?? 'Unknown'}`,
    `  Strengths:    ${safeArr(prediction.profile?.strengths).join(', ') || '—'}`,
    `  Weaknesses:   ${safeArr(prediction.profile?.weaknesses).join(', ') || '—'}`,
    '',
    '╔═══════════════════════════════════════════════╗',
    '║  AI USED:             Absolutely none.         ║',
    '║  SCIENTIFIC ACCURACY: 0%                       ║',
    '║  CONTEXT DETECTED BY: COCO-SSD + MobileNet     ║',
    '║  CERTIFIED BY:        International Institute  ║',
    '║                       of Absolutely Nothing    ║',
    '╚═══════════════════════════════════════════════╝',
    '',
    '⚠️  This report is 100% fake and for entertainment only.',
    '   Please do not make real life decisions based on this.',
    '   We beg you.',
    '',
    '   love404 — love404.fake',
  ]

  return lines.join('\n')
}

export function downloadTextReport(prediction, context, uploadMode, personA, personB) {
  const text = buildPlainTextReport(prediction, context, uploadMode, personA, personB)
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = `love404-${context}-report.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

export function copyReportToClipboard(prediction, context, uploadMode, personA, personB) {
  const text = buildPlainTextReport(prediction, context, uploadMode, personA, personB)
  return navigator.clipboard.writeText(text)
}
